AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'

# Layout
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

# Metrics
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

# Style
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
