version: '2'

services:
  app:
    build: docker/app
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - UMAKADATA_DATABASE_HOST=db
      - UMAKADATA_REDIS_HOST=redis
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
      - app_node_modules:/app/node_modules
      - app_public_assets:/app/public/assets
      - app_public_packs:/app/public/packs
      - app_tmp:/app/tmp
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - db
      - redis

  db:
    image: postgres:11.4
    environment:
      - POSTGRES_USER=${UMAKADATA_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${UMAKADATA_DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:5.0
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  app_bundle:
    driver: local
  app_node_modules:
    driver: local
  app_public_assets:
    driver: local
  app_public_packs:
    driver: local
  app_tmp:
    driver: local
