version: '2'
 
services:
  db:
    image: postgres:9.5
  web:
    build: .
    environment:
      - RAILS_ENV=production
    volumes:
      - .:/myapp
      - bundle:/myapp/web/vendor/bundle
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - db

volumes:
  bundle:
    driver: local
