version: '2'

services:
  nginx:
    image: nginx:1.17
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_www:/var/www
    ports:
      - 80:80
    depends_on:
      - app

  postgres:
    image: postgres:11.4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - POSTGRES_USER=${UMAKADATA_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${UMAKADATA_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  app:
    build: docker/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - UMAKADATA_DATABASE_HOST=postgres
      - UMAKADATA_REDIS_HOST=redis
    volumes:
      - .:/app
      - app_bundle:/app/vendor/bundle
      - app_node_modules:/app/node_modules
      - app_public_assets:/app/public/assets
      - app_public_packs:/app/public/packs
      - app_tmp:/app/tmp
      - app_www:/var/www
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_bundle:
    driver: local
  app_node_modules:
    driver: local
  app_public_assets:
    driver: local
  app_public_packs:
    driver: local
  app_tmp:
    driver: local
  app_www:
    driver: local
