version: '2'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_www:/var/www
    ports:
      - 80:80
    depends_on:
      - app

  postgres:
    image: postgres:11.4
    environment:
      - POSTGRES_USER=umakadata
      - POSTGRES_PASSWORD=${UMAKADATA_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  app:
    build: docker/app
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - UMAKADATA_DATABASE_HOST=postgres
      - UMAKADATA_DATABASE_PASSWORD=${UMAKADATA_DATABASE_PASSWORD}
    volumes:
      - .:/app
      - app_bundle:/app/vendor/bundle
      - app_tmp:/app/tmp
      - app_www:/var/www
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_bundle:
    driver: local
  app_tmp:
    driver: local
  app_www:
    driver: local
