version: '2'
 
services:
  db:
    image: postgres:9.5
    expose:
      - "5432" 
  web:
    build: .
    env_file: secrets.env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
