# cron = "Seconds Minutes Hours Days Months DayOfWeek"
schedule_checker:
  class: CrawlerRunnerJob
  queue: runner
  cron: '0 0 * * * *'
  description: 'This job checks whether if it is time to start crawler every hour.'

schedule_archiver:
  class: ArchiveJob
  queue: archiver
  cron: '0 0 0 1 * *'
  description: 'This job archives old data and clean database once a month.'

schedule_profiler:
  class: ProfilerRunnerJob
  queue: runner
  cron: '0 0 3 1 * *'
  description: 'This job obtain several statistics for SPARQL endpoints.'
