source 'https://rubygems.org'

gem 'umakadata', git: 'https://github.com/dbcls/umakadata_gem.git'

# web framework
gem 'rails', '4.2.10'
gem 'draper'

# optimization
gem 'turbolinks'

# database
gem 'sqlite3'
gem 'pg', '~> 0.20.0'

# middle ware
gem 'foreman'
gem 'unicorn'

# HTML/CSS framework
gem 'sass-rails', '~> 5.0'
gem 'slim-rails'

# javascript
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'therubyracer', platforms: :ruby
gem 'uglifier', '>= 1.3.0'

# utils
gem 'active_median'
gem 'activerecord-session_store'
gem 'google-analytics-rails'
gem 'jbuilder', '~> 2.0'
gem 'octokit'
gem 'omniauth'
gem 'omniauth-github'
gem 'simple_form'
gem 'whenever'

# admin
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem 'cancan'
gem 'pundit'

# linked data
gem 'json-ld'

# documentation
gem 'sdoc', '~> 0.4.0', group: :doc

# debug & testing
group :development do
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-doc'
end
